version: "3"
services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0
    restart: no
    ports:
     - "8003:8000"
    volumes:
     - ./app:/app # modified here to take into account the new app path